### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021A087AFD30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极 拒绝，无法连接。'))

### ISSUE THREAD

**Issue by RidiculousRonZzz** [tuteng0915/ChatGLM-ArtAgent#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021A087AFD30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极 拒绝，无法连接。'))

### Steps To Reproduce

I got the error when I tried to chat with GLM / generate a photo.

### Environment

```markdown
windows11
```

**Comment by tuteng0915** [comment]
这个报错是来源于API端口调用问题，已在 README 报错答疑添加
